### ISSUE TITLE
Fade between videos

### ISSUE THREAD

**Issue by CShouse1970** [JE-Random-Tech/ProJEcts#3]
Can you make it to where the videos faded into on another when the videos switch instead of jumping straight to the video selected?  Thanks.

**Comment by seinos** [comment]
Unfortunately, I did not find any opacity flag for the omxplayer. I think the most versatile approach is to put the video you want to switch to on the highest layer and then add the opacity there. However, I do not know if the player supports alpha channels or which format to use. Another idea would be to use the --crop flag of omxplayer and steadily increase the size. However keep in mind that the GPU of the raspi is quite limited.

**Comment by JE-Random-Tech** [comment]
Unfortunately, I did not find any opacity flag for the omxplayer. I think the most versatile approach is to put the video you want to switch to on the highest layer and then add the opacity there. However, I do not know if the player supports alpha channels or which format to use. Another idea would be to use the --crop flag of omxplayer and steadily increase the size. However keep in mind that the GPU of the raspi is quite limited.

**Comment by CShouse1970** [comment]
Thanks.  I'm scrapping the fade idea but I was wanting to have this run  on boot.  I'm making an interactive display for a museum and I need it to work when the system boots up for if and when the electric goes down or is turned off.  How would I  do this?

**Comment by JE-Random-Tech** [comment]
Sorry for my late reply. I saw you opened a new issue. I answered there. I hope that helped.

**Comment by JE-Random-Tech** [comment]
continued in #4
